edition = "2021"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Horizontal"
wrap_comments = true
brace_style = "SameLineWhere"
fn_params_layout = "Vertical"
fn_call_width = 30
